### PR TITLE
fix `napi_async_work` prevent Node.js from exiting

### LINKED ISSUE #25: AsyncWorkers prevent Node.js from exiting
lovell/sharp#3522

https://github.com/lovell/sharp/pull/3522/files#diff-f1d20c9f37b79bd0729e7379d212de61e425488d7ceb987ed964326f874d7c43R44-R66

### PR DESCRIPTION
**Pull request by toyobayashi**
fixes #25

### CODE REVIEW

**Comment by toyobayashi** [comment]
seems this breaks cleanup hooks at process beforeExit event ...

**Comment by toyobayashi** [comment]
immediately call `napi_cancel_async_work` after `napi_queue_async_work` may cause error, in random probability

**Comment by RReverser** [comment]
The worker ref/unref logic here seems a bit complicated TBH, especially with various checks, `postMessage` and so on.

Node.js doesn't care which handle keeps the process alive, so you don't need to `.ref()` all individual workers when running an async operation - the MessagePort from https://github.com/toyobayashi/emnapi/commit/a71cc2585096206f52644dae21b9b9eaf86e44b9 should be enough.

From worker side, it should be enough to only `.unref()` workers once when an emnapi thread is created, and leave the rest of ref/unref to that MessagePort. I think that would simplify the code quite a bit.

**Comment by toyobayashi** [comment]
Done.

**Comment by RReverser** [comment]
Nice, looks much simpler!

**Comment by RReverser** [comment]
By the way, I wanted to ask - why did you need `worker = worker.worker || worker`? Isn't `PThread.pthreads[id]` always a Worker already?

**Comment by toyobayashi** [comment]
This is for backward compatibility, I remember emscripten once refactored `PThread`.

https://github.com/emscripten-core/emscripten/pull/17492

**Pull request merged**
